### PR TITLE
Fixes #9(Added content in about template)

### LINKED ISSUE #9: Add content in about template.
Currently the about template is blank.Add information pertaining to the portal as mentioned in the readme.Proper grammar and documentation writing is highly encouraged.

image

### PR DESCRIPTION
**Pull request by Archies11**
Link: https://archies11.github.io/outpassfinal/

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@Archies11 Since this project setup is in django you will have to provide ss 😅

**Comment by Archies11** [comment]
capture

I am not sure if i can add Css styling to this page since it does not contain the body or head tags.

**Comment by Archies11** [comment]
Is there a link that might help me solve this issue the required way? I am not sure where am I comitting a mistake.

**Comment by Jigar3** [comment]
@Archies11  https://tutorial.djangogirls.org/en/django_start_project/ This link will help you understand django. Talking about the current issue, you could make a new css file and link that in leave/base.html. You can see that in leave/about.html there is
`{% extends 'leave/base.html' %}`
which means about.html is extending the stuff in base.html

**Comment by Archies11** [comment]
Okay,thank you. I will try to implement the same.

**Comment by Archies11** [comment]
New PR : https://github.com/opencodeiiita/outpassfinal/pull/14

**Pull request closed without merging**
