### PR TITLE
#2 LOGO

### PR DESCRIPTION
**Pull request by palak2001**
out

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
in my opinion this logo is good in the sense it represents outpass. But that sad emoji just makes it bad. It shouldn't be like that. It can be replaced with something good, maybe a happier version.

Pitching in @aswinzz for his review.

**Comment by palak2001** [comment]
Ok :p

**Comment by palak2001** [comment]
out

**Comment by Tlazypanda** [comment]
@palak2001 LGTM @Anupam-dagar @aswinzz  Kindly review

**Comment by Anupam-dagar** [comment]
resolved in #16

**Pull request closed without merging**
